from __future__ import annotations

from collections.abc import Iterator
from functools import lru_cache

from llama_cpp import Llama

from app.core.config import settings


@lru_cache(maxsize=1)
def get_llm() -> Llama:
    """Load and cache the local Llama model (Vulkan backend).

    The model is loaded once at first call and reused across all requests.
    n_ctx is capped at 4096 to prevent KV cache OOM on 16 GB shared RAM.

    Returns:
        A ready-to-use Llama instance with Vulkan offload enabled.
    """
    return Llama(
        model_path=settings.model_path,
        n_ctx=settings.n_ctx,
        n_gpu_layers=settings.n_gpu_layers,
        verbose=False,
    )


def stream_local(messages: list[dict[str, str]]) -> Iterator[str]:
    """Stream tokens from the local Llama model.

    Runs synchronously — wrap in asyncio.to_thread() when calling from
    an async context to avoid blocking the FastAPI event loop.

    Args:
        messages: OpenAI-format chat messages list.

    Yields:
        Token strings as they are generated by the model.
    """
    llm = get_llm()
    stream = llm.create_chat_completion(
        messages=messages,
        stream=True,
        max_tokens=settings.max_tokens,
    )
    for chunk in stream:
        delta: dict[str, str] = chunk["choices"][0].get("delta", {})
        content = delta.get("content", "")
        if content:
            yield content
